### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by mrhdias** [maxcountryman/tower-sessions-stores#39]
cargo add tower-sessions-sqlx-store -F postgres
    Updating crates.io index
      Adding tower-sessions-sqlx-store v0.13.0 to dependencies
             Features:
             + postgres
             - mysql
             - sqlite
    Updating crates.io index
error: failed to select a version for `libsqlite3-sys`.
    ... required by package `sqlx-sqlite v0.8.0`
    ... which satisfies dependency `sqlx-sqlite = "=0.8.0"` of package `sqlx v0.8.0`
    ... which satisfies dependency `sqlx = "^0.8.0"` of package `tower-sessions-sqlx-store v0.13.0`
    ... which satisfies dependency `tower-sessions-sqlx-store = "^0.13.0"` of package `store v0.1.0 (/home/hdias/Work/Development/Gurubeet/workspace/store)`
versions that meet the requirements `^0.28.0` are: 0.28.0

the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.27.0`
    ... which satisfies dependency `libsqlite3-sys = "^0.27.0"` of package `sqlx-sqlite v0.7.4`
    ... which satisfies dependency `sqlx-sqlite = "=0.7.4"` of package `sqlx v0.7.4`
    ... which satisfies dependency `sqlx = "^0.7.4"` of package `store v0.1.0 (/home/hdias/Work/Development/Gurubeet/workspace/store)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the `links = "sqlite3"` value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

**Comment by maxcountryman** [comment]
You need to also update sqlx-sqlite if you want to use the latest version of sqlx.

**Comment by waynr** [comment]
The problem here is that the version of `sqlx` that the OP depended on mismatches what `tower-sessions-sqlx-store` depends on. The fix for @mrhdias is not to update `sqlx-sqlite` as suggested by the @maxcountryman, but to update `sqlx`.

I am encountering a similar issue, except that in my case there is one addional culprit involved -- the latest version of `sea-orm` depends on `sqlx = ^0.7`, which results in the same dependency resolution error. Since I can't simply update to a newer version of `sea-orm`, my only option is to downgrade my `tower-sessions-sqlx-store` version to the previous release, eg `cargo add tower-sessions-sqlx-store@0.12 -F postgres`.
